### ISSUE TITLE
Can't install libreoffice-3.4.5.2

### ISSUE THREAD

**Issue by masavini** [kamadorueda/four-shells#5]
### Summary and *bug* behavior
I can't install an old libreoffice version

### Steps to reproduce
nix-env -i libreoffice -f https://github.com/NixOS/nixpkgs/archive/1fef26d8f7907acd40ff631f158223bc3769db06.tar.gz

### What is the expected *correct* behavior?
I'd expect libreoffice to be installed

### Relevant logs and/or screenshots
```
[...]
building '/nix/store/2xzasvpnhqcnbrbzdc6n2wvb9dysw89w-067201ea8b126597670b5eff72e1f66c-mythes-1.2.0.tar.gz.drv'...
error checking the existence of http://nixos.org/tarballs/md5/067201ea8b126597670b5eff72e1f66c:
curl: (35) error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version

trying http://dev-www.libreoffice.org/src/067201ea8b126597670b5eff72e1f66c-mythes-1.2.0.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   185  100   185    0     0   1909      0 --:--:-- --:--:-- --:--:--  4302
curl: (35) error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version
error: cannot download 067201ea8b126597670b5eff72e1f66c-mythes-1.2.0.tar.gz from any mirror
builder for '/nix/store/2xzasvpnhqcnbrbzdc6n2wvb9dysw89w-067201ea8b126597670b5eff72e1f66c-mythes-1.2.0.tar.gz.drv' failed with exit code 1
cannot build derivation '/nix/store/idjc2w7spfl27niiccd8p1q3fqxc5r28-libreoffice-3.4.5.2.drv': 1 dependencies couldn't be built
```

### Possible fixes
I'm pretty new to nix and I can't guess any fix.
I just know I tried this installation in 2 different virtual machines (manjaro on vmware and ubuntu 20.04 on virtualbox) and the installation always fail with the same error.

## Merry Christmas!!

**Comment by kamadorueda** [comment]
I've been able to replicate the issue (with exactly the same failure)

This is the status of software builds across different Nix channels:

![image](https://user-images.githubusercontent.com/47480384/103163225-65fcd880-47c9-11eb-85e6-9693b84beb1c.png)

As you can see some packages fail, while others succeed

Packages in Nix are built by the community in a best-effort basis. Normally they work excellently, but as versions get older a network protocol like [TLSv1 can become insecure](https://www.globalsign.com/en/blog/disable-tls-10-and-all-ssl-versions) and make builds that depend on such protocol fail, which is what happens to libreoffice 3:

![image](https://user-images.githubusercontent.com/47480384/103163276-17037300-47ca-11eb-8b8b-67a7c59e66a8.png)

At NixDB we are committed to index all packages versions and history, and we did! it just happens that it's too old and it's no longer secure to build it

Merry christmas to you too!

**Comment by masavini** [comment]
Hi,
thanks for your reply.
Since Nix packages are built by the community would it be possibile to contribute and update that particular package with a more recent version of curl?

**Comment by kamadorueda** [comment]
If you want version 3 **only** for your use, doing as less modifications as possible, you could:
- clone the [nixpkgs repository](https://github.com/NixOS/nixpkgs)
- checkout revision `1fef26d8f7907acd40ff631f158223bc3769db06`
- edit the source code in order to make it work, which is located at [/pkgs/applications/office/openoffice/libreoffice.nix](https://github.com/NixOS/nixpkgs/blob/1fef26d8f7907acd40ff631f158223bc3769db06/pkgs/applications/office/openoffice/libreoffice.nix)

Then you can do `nix-env -i libreoffice -f /path/to/your/local/nixpkgs/repo` to install the libreoffice you just modified

You can also fork the repo, and do `nix-env -i libreoffice -f url-of-your-fork`

---

If you want to contribute the package for the community, take into account that currently the package is at version 7, so it's very well maintained. I think nixpkgs maintainers will only accept a PR for libreoffice v3 if there is a good reason for the general community to use it instead of the last version

Packages are added this way:

- They are added to the top-level: https://github.com/NixOS/nixpkgs/blob/nixos-20.09/pkgs/top-level/all-packages.nix#L21573, a new version would be like `libreoffice3 = ...`
- Then you add your code in this folder: https://github.com/NixOS/nixpkgs/tree/nixos-20.09/pkgs/applications/office/libreoffice

The (failing) source code for version 3 is:
- https://github.com/NixOS/nixpkgs/blob/1fef26d8f7907acd40ff631f158223bc3769db06/pkgs/applications/office/openoffice/libreoffice.nix
- https://github.com/NixOS/nixpkgs/blob/1fef26d8f7907acd40ff631f158223bc3769db06/pkgs/applications/office/openoffice/libreoffice-srcs.nix

You can use that as inspiration

---

Either alternatives may not be easy, you decide if it's worth the effort

The maintainer seems to be [raskin](https://github.com/NixOS/nixpkgs/blob/nixos-20.09/pkgs/applications/office/libreoffice/default.nix#L425)

This is his contact: https://github.com/NixOS/nixpkgs/blob/nixos-20.09/maintainers/maintainer-list.nix#L6932
